# .github/workflows/daily_scrape.yml

name: Daily Watch Deal Scrape

on:
  # Esegue ogni giorno alle 01:00 UTC (puoi cambiare l'orario)
  schedule:
    - cron: '0 1 * * *'
  # Permette anche di lanciarlo manualmente dalla tab "Actions" di GitHub
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest # Usa una macchina virtuale Linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Scarica il tuo codice

    - name: Set up Python
      uses: actions/setup-python@v4 # Installa Python
      with:
        python-version: '3.10' # Specifica la versione di Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests firebase-admin
        
    - name: Create and Verify Firebase Service Account Key
  run: 
    echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ${{ github.workspace }}/serviceAccountKey.json
    echo "--- Verifying file existence ---"
    ls -l ${{ github.workspace }}
      # Questo comando prende il secret di GitHub e ricrea il file .json nella macchina virtuale

    - name: Run the Scraper
  run: python ${{ github.workspace }}/scraper_v3.1.py # Esegue il nostro script!
